# Generated by Django 3.0.5 on 2021-05-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Contact_Info', models.IntegerField(blank=True, default=900, null=True)),
                ('Subject', models.CharField(max_length=122)),
                ('Query', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Model_Name', models.CharField(max_length=122)),
                ('Information', models.CharField(max_length=122)),
                ('Price', models.IntegerField()),
                ('Date_of_Purchase', models.DateField()),
                ('Branch', models.CharField(choices=[('malad (e)', 'Malad (E)'), ('malad (w)', 'Malad (W)'), ('goregoan', 'Goregoan'), ('andheri (e)', 'Abdheri (E)'), ('andheri (w)', 'Abdheri (W)')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback_User', models.TextField()),
                ('Customer_Satisfied', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='New_Registers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=122)),
                ('Last_Name', models.CharField(max_length=122)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField(blank=True, null=True)),
                ('Branch', models.CharField(choices=[('malad (e)', 'Malad (E)'), ('malad (w)', 'Malad (W)'), ('goregoan', 'Goregoan'), ('andheri (e)', 'Abdheri (E)'), ('andheri (w)', 'Abdheri (W)')], max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=122)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Branch', models.CharField(choices=[('malad (e)', 'Malad (E)'), ('malad (w)', 'Malad (W)'), ('goregoan', 'Goregoan'), ('andheri (e)', 'Abdheri (E)'), ('andheri (w)', 'Abdheri (W)')], max_length=100)),
                ('Age', models.IntegerField()),
                ('Date_of_joining', models.DateField()),
                ('Total_Annual_Salary', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Jan_Salary', models.CharField(blank=True, choices=[('done', 'DONE'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('Feb', models.CharField(blank=True, choices=[('done', 'DONE'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('March', models.CharField(blank=True, choices=[('done', 'DONE'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('April', models.CharField(blank=True, choices=[('done', 'DONE'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('May', models.CharField(blank=True, choices=[('done', 'DONE'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('June', models.CharField(blank=True, choices=[('done', 'DONE'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('July', models.CharField(blank=True, choices=[('done', 'DONE'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('August', models.CharField(blank=True, choices=[('done', 'DONE'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('Sep', models.CharField(blank=True, choices=[('done', 'DONE'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('Oct', models.CharField(blank=True, choices=[('done', 'DONE'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('Nov', models.CharField(blank=True, choices=[('done', 'DONE'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('Dec', models.CharField(blank=True, choices=[('done', 'DONE'), ('pending', 'PENDING')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=122)),
                ('Date_of_joining', models.DateField()),
                ('Age', models.IntegerField()),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Branch', models.CharField(choices=[('malad (e)', 'Malad (E)'), ('malad (w)', 'Malad (W)'), ('goregoan', 'Goregoan'), ('andheri (e)', 'Abdheri (E)'), ('andheri (w)', 'Abdheri (W)')], max_length=100)),
                ('Year', models.IntegerField()),
                ('Jan_Fees', models.CharField(blank=True, choices=[('paid', 'PAID'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('Feb', models.CharField(blank=True, choices=[('paid', 'PAID'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('March', models.CharField(blank=True, choices=[('paid', 'PAID'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('April', models.CharField(blank=True, choices=[('paid', 'PAID'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('May', models.CharField(blank=True, choices=[('paid', 'PAID'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('June', models.CharField(blank=True, choices=[('paid', 'PAID'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('July', models.CharField(blank=True, choices=[('paid', 'PAID'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('August', models.CharField(blank=True, choices=[('paid', 'PAID'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('Sep', models.CharField(blank=True, choices=[('paid', 'PAID'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('Oct', models.CharField(blank=True, choices=[('paid', 'PAID'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('Nov', models.CharField(blank=True, choices=[('paid', 'PAID'), ('pending', 'PENDING')], max_length=100, null=True)),
                ('Dec', models.CharField(blank=True, choices=[('paid', 'PAID'), ('pending', 'PENDING')], max_length=100, null=True)),
            ],
        ),
    ]
