# Generated by Django 3.0.5 on 2021-05-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0002_delete_admin_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetter',
        ),
    ]
