# Generated by Django 3.0.5 on 2021-05-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0003_delete_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Name',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
