# Generated by Django 3.0.5 on 2021-05-28 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0004_feedback_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Customer_Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
    ]
