# Generated by Django 3.0.5 on 2021-05-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0005_feedback_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Customer_Name',
        ),
    ]
