# Generated by Django 3.0.5 on 2021-05-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0006_remove_feedback_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Name',
            new_name='Customer_Name',
        ),
    ]
