# Generated by Django 3.0.5 on 2021-05-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0007_auto_20210528_2055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feedback_User',
        ),
    ]
