# Generated by Django 3.0.5 on 2021-05-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0008_auto_20210528_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_user',
            old_name='Feedback_User',
            new_name='Feedback',
        ),
    ]
