# Generated by Django 3.0.5 on 2021-06-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0009_auto_20210528_2109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Database',
            new_name='Customer_Database',
        ),
    ]
