# Generated by Django 3.0.5 on 2021-06-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0010_auto_20210605_2013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New_Registers',
        ),
    ]
