# Generated by Django 3.0.5 on 2021-06-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0011_delete_new_registers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainers',
            old_name='Year',
            new_name='TYear',
        ),
        migrations.AlterField(
            model_name='customer_database',
            name='Year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
