# Generated by Django 3.0.5 on 2021-06-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0012_auto_20210626_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Full_Name_C',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
