# Generated by Django 3.0.5 on 2021-06-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0014_auto_20210626_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_user',
            old_name='Customer_Satisfied',
            new_name='Customer_Satisfaction',
        ),
    ]
