# Generated by Django 3.0.5 on 2021-06-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0015_auto_20210626_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Contact_Info',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
